# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='circle_id',
        ),
        migrations.RemoveField(
            model_name='rolefiller',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='rolefiller',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleFiller',
        ),
    ]
