# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0002_auto_20161119_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('glassfrog_id', models.IntegerField(unique=True)),
                ('glassfrog_url', models.CharField(max_length=200)),
                ('last_imported', models.DateTimeField()),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.Circle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleFiller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_points', models.FloatField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.Role')),
            ],
        ),
    ]
