# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0003_role_rolefiller'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolefiller',
            name='last_imported',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
