# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0004_rolefiller_last_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='super_circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aps.Circle'),
        ),
        migrations.AddField(
            model_name='role',
            name='supporting_circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_circle', to='aps.Circle'),
        ),
    ]
