# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0005_auto_20161121_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aps.Circle'),
        ),
    ]
