# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0009_auto_20161122_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='super_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_circles', to='aps.Circle'),
        ),
        migrations.AlterField(
            model_name='role',
            name='supporting_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supported_role', to='aps.Circle'),
        ),
    ]
